security:
    # Configuration des hashers de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des providers pour charger les utilisateurs
    providers:
        # Chargement des utilisateurs depuis la base de données
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        # Désactivation de la sécurité pour les environnements de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            lazy: true
            provider: app_user_provider
            # Authentification via formulaire avec gestionnaire de succès
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginRedirectHandler
            # Déconnexion
            logout:
                path: app_logout
                target: /
            # Mécanisme "Se souvenir de moi"
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            # Point d'entrée pour la sécurité
            entry_point: App\Security\LoginFormAuthenticator

    # Règles d'accès (access control)
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

# Configuration spécifique aux tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
